### ISSUE TITLE
Potential bug when selecting "Maintain Weight"

### ISSUE THREAD

**Issue by kastnerp** [jmd543/Final_Project#1]
Hi Jamie,

I just tested your implementation and noticed that I cannot select exercise options `('Arms', 'Legs', 'Back', 'Abs', 'Glutes', 'Posture')` while I have `Maintain Weight` selected. When I do, the page jumps back to `Get Results!`

Best,

Patrick

**Comment by jmd543** [comment]
Sorry! This has been fixed - didn't realize it would do that when you tried to select an option.

Thank you!
Jamie
